### ISSUE TITLE
no libz3java in java.library.path

### ISSUE THREAD

**Issue by ivy-lv11** [rongpan/RFixer#1]
hi, when I ran the command 
```
java -jar target/regfixer.jar --mode 1 fix --file tests/clean_AutoTutor/test6.txt
```
in the terminal on my m1 MacBook Pro , an error happened. Exception in thread "main" java.lang.UnsatisfiedLinkError: no libz3java in java.library.path: I have download the dependencies and built the target successfully. Could you give a solution to the problem? Thanks!

**Comment by 5han7anu-S** [comment]
You need to build Z3 with Java bindings and have that package in your Path
https://github.com/Z3Prover/z3.

**Comment by lorisdanto** [comment]
Somehow I saw this now. Thanks for the answer @ShantanuPSinha

**Comment by 5han7anu-S** [comment]
Just to add to this, I had to rebuild the project and it doesn't work with the latest version of Z3 (segfaults).

There is a pre-compiled libz3java.so in the project root. Symlink it to /usr/lib and everything should work
